task:
  container:
    image: golang:1.14
  name: Unit Test
  script: go test ./...

task:
  container:
    image: golang:1.14
  name: intergration
  script: |
    cd cmd/diary && go install . && \
    cd ./testdata/intergration && \
    ./intergration_test.sh

task:
  container:
    image: golangci/golangci-lint:v1.30.0
  name: source lint
  script: make lint_go

task:
  container:
    image: node:14
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm install
  name: markdown lint
  script: npm run lint
